### ISSUE TITLE
errors while installing 

### ISSUE THREAD

**Issue by shuuichiakai** [darryldecode/laravelbackend#6]
hi, i get errors while installing laravelbackend.
[RuntimeException]  
  Could not load package intervention/image in http://packagist.org: [Unexpec  
  tedValueException] Could not parse version constraint 4.x.x: Invalid versio  
  n string "4.x.x"         

and 

 [UnexpectedValueException]  
  Could not parse version constraint 4.x.x: Invalid version string "4.x.x"

Please help me fix them.

**Comment by darryldecode** [comment]
hi @shuuichiakai , are you installing this package with a fresh installation of laravel 5.1~? Because the error looks like there is already a "intervention/image" package installed on your current laravel application which the version is not compatible with this package..

**Comment by shuuichiakai** [comment]
how to Preferr a fresh install of laravel 5.1. is this "composer create-project laravel/laravel --prefer-dist" ? 
i did but still get errors. :(

**Comment by darryldecode** [comment]
hi @shuuichiakai , I found out that the problem is not actually in the package but in the composer it self.. Please update your composer and then try again. For more info about updating your composer installation please see the link below. Thanks! :)

https://getcomposer.org/doc/03-cli.md#update
